mysql:
  image: mysql:5.6
  ports:
  - "3306:3306"
  environment:
  - "MYSQL_ROOT_PASSWORD=password"
  - "MYSQL_USER=sa"
  - "MYSQL_PASSWORD=password"
  restart: always

eureka:
  build: ./Eureka-Server
  ports:
  - "8761:8761"
  restart: always

product-service:
  build: ./Product-Service
  ports:
  - "8081:8080"
  links:
  - "mysql"
  - "eureka"
  restart: always
  
review-service:
  build: ./Review-Service
  ports:
  - "8080:8080"
  links:
  - "mysql"
  - "eureka"
  restart: always

zuul-gateway:
  build: ./zuul-gateway
  ports:
  - "8762:8762"
  links:
  - "mysql"
  - "eureka"
  - "product-service"
  - "review-service"
  restart: always
  